/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendas;

/**
 *
 * @author Marcelo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    
    public MenuPrincipal() {
         
        initComponents();
        //setSize(940, 420);
       setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuantS2 = new javax.swing.JTextField();
        QuantS3 = new javax.swing.JTextField();
        QuantS4 = new javax.swing.JTextField();
        QuantS1 = new javax.swing.JTextField();
        QuantAD1 = new javax.swing.JTextField();
        QuantAD2 = new javax.swing.JTextField();
        QuantAD3 = new javax.swing.JTextField();
        TXTValorPago = new javax.swing.JTextField();
        BtnValorLiquido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lucro = new javax.swing.JLabel();
        LblValorTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnTroco = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        QuantAD4 = new javax.swing.JTextField();
        btnConcluir = new javax.swing.JButton();
        BtnPromocao1 = new javax.swing.JButton();
        LblTroco1 = new javax.swing.JLabel();
        zfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(940, 420));
        getContentPane().setLayout(null);

        QuantS2.setText("0");
        QuantS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantS2ActionPerformed(evt);
            }
        });
        getContentPane().add(QuantS2);
        QuantS2.setBounds(130, 110, 60, 30);

        QuantS3.setText("0");
        getContentPane().add(QuantS3);
        QuantS3.setBounds(130, 150, 60, 30);

        QuantS4.setText("0");
        getContentPane().add(QuantS4);
        QuantS4.setBounds(130, 190, 60, 30);

        QuantS1.setText("0");
        getContentPane().add(QuantS1);
        QuantS1.setBounds(130, 70, 60, 30);

        QuantAD1.setText("0");
        getContentPane().add(QuantAD1);
        QuantAD1.setBounds(340, 70, 60, 30);

        QuantAD2.setText("0");
        getContentPane().add(QuantAD2);
        QuantAD2.setBounds(340, 110, 60, 30);

        QuantAD3.setText("0");
        getContentPane().add(QuantAD3);
        QuantAD3.setBounds(340, 150, 60, 30);

        TXTValorPago.setText("0");
        TXTValorPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTValorPagoActionPerformed(evt);
            }
        });
        getContentPane().add(TXTValorPago);
        TXTValorPago.setBounds(140, 270, 60, 30);

        BtnValorLiquido.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        BtnValorLiquido.setText("Aplicar sem promoçao");
        BtnValorLiquido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValorLiquidoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnValorLiquido);
        BtnValorLiquido.setBounds(250, 320, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel2.setText("chocolate");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Quantidade:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 20, 120, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel8.setText("Valor pago R$:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 270, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel9.setText("Valor Total R$:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 240, 130, 20);

        lucro.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lucro.setText("00,00");
        getContentPane().add(lucro);
        lucro.setBounds(270, 360, 60, 30);

        LblValorTotal.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        LblValorTotal.setText("00,00");
        getContentPane().add(LblValorTotal);
        LblValorTotal.setBounds(150, 240, 60, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setText("Sabores:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 20, 80, 20);

        BtnTroco.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        BtnTroco.setText("Troco R$:");
        BtnTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrocoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTroco);
        BtnTroco.setBounds(220, 250, 130, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel11.setText("sla");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 150, 70, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel13.setText("sla2");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 190, 70, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel14.setText("molho 1");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(220, 70, 70, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel15.setText("molho 2");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(220, 110, 70, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel16.setText("molho 3");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(220, 150, 70, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel17.setText("molho 4");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(220, 190, 70, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel18.setText("frango");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 70, 70, 20);

        QuantAD4.setText("0");
        getContentPane().add(QuantAD4);
        QuantAD4.setBounds(340, 190, 60, 30);

        btnConcluir.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        btnConcluir.setText("Concluir");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConcluir);
        btnConcluir.setBounds(10, 360, 220, 30);

        BtnPromocao1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        BtnPromocao1.setText("Aplicar com Promoçao");
        BtnPromocao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPromocao1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPromocao1);
        BtnPromocao1.setBounds(10, 320, 220, 30);

        LblTroco1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        LblTroco1.setText("00,00");
        getContentPane().add(LblTroco1);
        LblTroco1.setBounds(370, 250, 60, 30);

        zfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendas/halloween.jpg"))); // NOI18N
        getContentPane().add(zfundo);
        zfundo.setBounds(0, 0, 940, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTValorPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTValorPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTValorPagoActionPerformed

    private void BtnTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrocoActionPerformed
        float total=Float.parseFloat(LblValorTotal.getText());
        float pago=Float.parseFloat(TXTValorPago.getText());
        float troco=pago-total;
        LblTroco1.setText(Float.toString(troco) );
        
    }//GEN-LAST:event_BtnTrocoActionPerformed

    private void BtnValorLiquidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValorLiquidoActionPerformed

  double TS1=Integer.parseInt(QuantS1.getText())*5.50; double TAd1=Integer.parseInt(QuantAD1.getText())*0.50;
  double TS2=Integer.parseInt(QuantS2.getText())*5.50; double TAd2=Integer.parseInt(QuantAD2.getText())*0.50;
  double TS3=Integer.parseInt(QuantS3.getText())*5.50; double TAd3=Integer.parseInt(QuantAD3.getText())*0.50;
  double TS4=Integer.parseInt(QuantS4.getText())*5.50; double TAd4=Integer.parseInt(QuantAD4.getText())*0.50;
  double total= TS1+TS2+TS3+TS4+TAd1+TAd2+TAd3+TAd4;
   
  LblValorTotal.setText(Double.toString(total));
  
    }//GEN-LAST:event_BtnValorLiquidoActionPerformed

    private void QuantS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantS2ActionPerformed

    private void BtnPromocao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPromocao1ActionPerformed
        // TODO add your handling code here:
  double TS1=Integer.parseInt(QuantS1.getText())*4.50; double TAd1=Integer.parseInt(QuantAD1.getText())*0.25;
  double TS2=Integer.parseInt(QuantS2.getText())*4.50; double TAd2=Integer.parseInt(QuantAD2.getText())*0.25;
  double TS3=Integer.parseInt(QuantS3.getText())*4.50; double TAd3=Integer.parseInt(QuantAD3.getText())*0.25;
  double TS4=Integer.parseInt(QuantS4.getText())*4.50; double TAd4=Integer.parseInt(QuantAD4.getText())*0.25;
  double total= TS1+TS2+TS3+TS4+TAd1+TAd2+TAd3+TAd4;
   
  LblValorTotal.setText(Double.toString(total));
    }//GEN-LAST:event_BtnPromocao1ActionPerformed

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        // TODO add your handling code here:
        //Valores a serem Guardados/Salvos
        int ContS1 =+Integer.parseInt(QuantS1.getText());
        int ContS2 =+Integer.parseInt(QuantS2.getText());
        int ContS3 =+Integer.parseInt(QuantS3.getText());
        int ContS4 =+Integer.parseInt(QuantS4.getText());
      float obitido=Float.parseFloat(LblValorTotal.getText());
       float lucroF =+obitido;
        //Nao precisam ser Salvos
       lucro.setText(Float.toString(lucroF));
        QuantS1.setText("0"); QuantAD1.setText("0"); 
        QuantS2.setText("0"); QuantAD2.setText("0");
        QuantS3.setText("0"); QuantAD3.setText("0");
        QuantS4.setText("0"); QuantAD4.setText("0");
        TXTValorPago.setText("0");
        LblValorTotal.setText("0"); 
        LblTroco1.setText("0");
        //Gerar PDF
        
    }//GEN-LAST:event_btnConcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
        //AQQQQQQQQQQUUUUUUUUUUIIIIIIIIIIIIIIIPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
       //C== Contador e Q==Quantidade
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPromocao1;
    private javax.swing.JToggleButton BtnTroco;
    private javax.swing.JButton BtnValorLiquido;
    private javax.swing.JLabel LblTroco1;
    private javax.swing.JLabel LblValorTotal;
    private javax.swing.JTextField QuantAD1;
    private javax.swing.JTextField QuantAD2;
    private javax.swing.JTextField QuantAD3;
    private javax.swing.JTextField QuantAD4;
    private javax.swing.JTextField QuantS1;
    private javax.swing.JTextField QuantS2;
    private javax.swing.JTextField QuantS3;
    private javax.swing.JTextField QuantS4;
    private javax.swing.JTextField TXTValorPago;
    private javax.swing.JButton btnConcluir;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lucro;
    private javax.swing.JLabel zfundo;
    // End of variables declaration//GEN-END:variables
}
